"""empty message

Revision ID: d02c4e72eb8b
Revises: 17df132cdd9a
Create Date: 2019-10-20 20:54:52.713101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02c4e72eb8b'
down_revision = '17df132cdd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_purchased', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('buys_for', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'user', ['buys_for'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'buys_for')
    op.drop_column('item', 'is_purchased')
    # ### end Alembic commands ###
